/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author hugo
 */
public class AnimalGUI extends javax.swing.JFrame {

    /**
     * Creates new form Animais
     */
    public AnimalGUI() {
        initComponents();
          setResizable(false);
       //Evita o fechamento da tela pelo clique no X.
       setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
       // Centraliza a tela criada no monitor
       setLocationRelativeTo(null);
       setSize(400, 400);
       // Insere titulo na tela
       setTitle("MeuPetShop");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jTNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTRaca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTEspecie = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTSexo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTTutor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTNascimento = new javax.swing.JTextField();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nome");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 100, 18);

        jTNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTNome);
        jTNome.setBounds(20, 30, 300, 24);

        jLabel2.setText("Raça");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 90, 18);
        getContentPane().add(jTRaca);
        jTRaca.setBounds(20, 90, 120, 24);

        jLabel3.setText("Especie");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 140, 140, 18);
        getContentPane().add(jTEspecie);
        jTEspecie.setBounds(20, 160, 120, 24);

        jButton1.setText("Gravar");
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 330, 90, 30);

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(320, 330, 72, 30);

        jLabel4.setText("Sexo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 70, 100, 20);

        jTSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTSexoActionPerformed(evt);
            }
        });
        getContentPane().add(jTSexo);
        jTSexo.setBounds(190, 90, 120, 24);

        jLabel5.setText("Id tutor");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(190, 140, 80, 18);

        jTTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTTutorActionPerformed(evt);
            }
        });
        getContentPane().add(jTTutor);
        jTTutor.setBounds(190, 160, 120, 24);

        jLabel6.setText("Nascimento");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 200, 130, 18);
        getContentPane().add(jTNascimento);
        jTNascimento.setBounds(20, 220, 150, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNomeActionPerformed

    private void jTSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTSexoActionPerformed

    private void jTTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTTutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTTutorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnimalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnimalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnimalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnimalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnimalGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jTEspecie;
    private javax.swing.JTextField jTNascimento;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTextField jTRaca;
    private javax.swing.JTextField jTSexo;
    private javax.swing.JTextField jTTutor;
    // End of variables declaration//GEN-END:variables
}
