/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.AnimalDAO;
import model.Animal;

/**
 *
 * @author hugo
 */
public class AnimalGUI extends javax.swing.JFrame {

    /**
     * Creates new form Animais
     */
    public AnimalGUI() {
        initComponents();
        setResizable(false);
        //Evita o fechamento da tela pelo clique no X.
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        // Centraliza a tela criada no monitor
        setLocationRelativeTo(null);
        setSize(400, 400);
        // Insere titulo na tela
        setTitle("MeuPetShop");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFRaca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFEspecie = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTFSexo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFTutor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFNascimento = new javax.swing.JTextField();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nome");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 100, 18);

        jTFNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTFNome);
        jTFNome.setBounds(20, 30, 300, 24);

        jLabel2.setText("Raça");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 90, 18);
        getContentPane().add(jTFRaca);
        jTFRaca.setBounds(20, 90, 120, 24);

        jLabel3.setText("Especie");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 140, 140, 18);
        getContentPane().add(jTFEspecie);
        jTFEspecie.setBounds(20, 160, 120, 24);

        jButton1.setText("Gravar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 330, 90, 30);

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(320, 330, 72, 30);

        jLabel4.setText("Sexo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 70, 100, 20);

        jTFSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFSexoActionPerformed(evt);
            }
        });
        getContentPane().add(jTFSexo);
        jTFSexo.setBounds(190, 90, 120, 24);

        jLabel5.setText("Id tutor");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(190, 140, 80, 18);

        jTFTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFTutorActionPerformed(evt);
            }
        });
        getContentPane().add(jTFTutor);
        jTFTutor.setBounds(190, 160, 120, 24);

        jLabel6.setText("Nascimento");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 200, 130, 18);
        getContentPane().add(jTFNascimento);
        jTFNascimento.setBounds(20, 220, 150, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTFNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNomeActionPerformed

    private void jTFSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFSexoActionPerformed

    private void jTFTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFTutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFTutorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nome = jTFNome.getText().toString().trim();
        String raca = jTFRaca.getText().toString().trim();
        String sexo = jTFSexo.getText().toString().trim();
        String especie = jTFEspecie.getText().toString().trim();
        String dataNascimento = jTFNascimento.getText().toString().trim();
        int idTutor = Integer.parseInt(jTFTutor.getText().trim());
        
        Animal animal = new Animal();
        
        animal.setNome(nome);
        animal.setRaca(raca);
        animal.setSexo(sexo);
        animal.setEspecie(especie);
        animal.setDataNascimento(dataNascimento);
        animal.setTutor(idTutor);
        
        AnimalDAO animalDao = new AnimalDAO();
        
        animalDao.inserirAnimal(animal);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnimalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnimalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnimalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnimalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnimalGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jTFEspecie;
    private javax.swing.JTextField jTFNascimento;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFRaca;
    private javax.swing.JTextField jTFSexo;
    private javax.swing.JTextField jTFTutor;
    // End of variables declaration//GEN-END:variables
}
