/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.ClienteDAO;
import model.Cliente;

/**
 *
 * @author hugo
 */
public class ClienteGUI extends javax.swing.JFrame {

    /**
     * Creates new form Clientes
     */
    public ClienteGUI() {
        initComponents();
          setResizable(false);
       //Evita o fechamento da tela pelo clique no X.
       setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
       // Centraliza a tela criada no monitor
       setLocationRelativeTo(null);
       setSize(810, 400);
       // Insere titulo na tela
       setTitle("MeuPetShop"); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFCpf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFTelefone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTFDataDeNacimento = new javax.swing.JTextField();
        jBGravar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nome");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 0, 46, 16);

        jTFNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTFNome);
        jTFNome.setBounds(20, 20, 310, 22);

        jLabel2.setText("CPF");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 50, 21, 16);
        getContentPane().add(jTFCpf);
        jTFCpf.setBounds(20, 70, 200, 22);

        jLabel4.setText("Email");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(350, 0, 29, 16);
        getContentPane().add(jTFEmail);
        jTFEmail.setBounds(350, 20, 310, 22);

        jLabel6.setText("Telefone");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(240, 50, 80, 20);
        getContentPane().add(jTFTelefone);
        jTFTelefone.setBounds(240, 70, 130, 20);

        jLabel7.setText("Data de Nascimento");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(380, 50, 150, 20);
        getContentPane().add(jTFDataDeNacimento);
        jTFDataDeNacimento.setBounds(380, 70, 200, 20);

        jBGravar.setText("Gravar");
        jBGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGravarActionPerformed(evt);
            }
        });
        getContentPane().add(jBGravar);
        jBGravar.setBounds(680, 10, 90, 30);

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(690, 60, 75, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Email", "Cpf", "Telefone", "Nascimento"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 750, 240);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTFNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNomeActionPerformed

    private void jBGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGravarActionPerformed
       String nome = jTFNome.getText().toString().trim();
       String email = jTFEmail.getText().toString().trim();
       String cpf = jTFCpf.getText().toString().trim();
       String telefone = jTFTelefone.getText().toString().trim();
       String dataNascimento = jTFDataDeNacimento.getText().toString().trim();
      
      Cliente cliente = new Cliente();
      cliente.setNome(nome);
      cliente.setEmail(email);
      cliente.setCpf(cpf);
      cliente.setTelefone(telefone);
      cliente.setDataNascimento(dataNascimento);
      
      ClienteDAO clienteDao = new ClienteDAO();
      clienteDao.inserirCliente(cliente);
    }//GEN-LAST:event_jBGravarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      jTFNome.setText(jTable1.getValueAt(jTable1.getSelectedRow(),1).toString());
      jTFEmail.setText(jTable1.getValueAt(jTable1.getSelectedRow(),2).toString());
      jTFCpf.setText(jTable1.getValueAt(jTable1.getSelectedRow(),3).toString());
      jTFTelefone.setText(jTable1.getValueAt(jTable1.getSelectedRow(),4).toString());
      jTFDataDeNacimento.setText(jTable1.getValueAt(jTable1.getSelectedRow(),5).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGravar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCpf;
    private javax.swing.JTextField jTFDataDeNacimento;
    private javax.swing.JTextField jTFEmail;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFTelefone;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
